# -*- coding: utf-8 -*-
"""Copie de Copie de Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pxrin1FR2I4vCKK2i_XffBqZ40XPW4v9

## **Regression Project**
We will build a regression model to predict house prices based on input features like area, bedrooms, and age.
The app will allow users to upload a dataset, train a model, and make predictions.
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression

# App title
st.title("House Price Prediction")

# Data upload
data = st.file_uploader("Upload your dataset (CSV)", type=["csv"])

if data is not None:
    df = pd.read_csv(data)
    st.write("Dataset Preview:", df.head())

    # Feature selection
    X = df.drop(columns=['price'])
    y = df['price']

    # Train model
    model = LinearRegression()
    model.fit(X, y)

    # User input
    st.write("Enter house details:")
    user_input = [st.number_input(f"{col}") for col in X.columns]

    # Prediction
    if st.button("Predict Price"):
        prediction = model.predict([user_input])
        st.success(f"Predicted House Price: ${prediction[0]:,.2f}")
